/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverRouteImport } from './routes/_driver'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DriverDeliveriesRouteImport } from './routes/_driver.deliveries'
import { Route as DriverEarningsRouteImport } from './routes/_driver.earnings'
import { Route as DriverHomeRouteImport } from './routes/_driver.home'
import { Route as DriverNotificationsRouteImport } from './routes/_driver.notifications'
import { Route as DriverProfileRouteImport } from './routes/_driver.profile'
import { Route as DriverSupportRouteImport } from './routes/_driver.support'
import { Route as DriverDeliveryOrderIdRouteImport } from './routes/_driver.delivery.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/_driver',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDeliveriesRoute = DriverDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHomeRoute = DriverHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DriverRoute,
} as any)
const DriverNotificationsRoute = DriverNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DriverRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverSupportRoute = DriverSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDeliveryOrderIdRoute = DriverDeliveryOrderIdRouteImport.update({
  id: '/delivery/$orderId',
  path: '/delivery/$orderId',
  getParentRoute: () => DriverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/deliveries': typeof DriverDeliveriesRoute
  '/earnings': typeof DriverEarningsRoute
  '/home': typeof DriverHomeRoute
  '/notifications': typeof DriverNotificationsRoute
  '/profile': typeof DriverProfileRoute
  '/support': typeof DriverSupportRoute
  '/delivery/$orderId': typeof DriverDeliveryOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/deliveries': typeof DriverDeliveriesRoute
  '/earnings': typeof DriverEarningsRoute
  '/home': typeof DriverHomeRoute
  '/notifications': typeof DriverNotificationsRoute
  '/profile': typeof DriverProfileRoute
  '/support': typeof DriverSupportRoute
  '/delivery/$orderId': typeof DriverDeliveryOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_driver': typeof DriverRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_driver/deliveries': typeof DriverDeliveriesRoute
  '/_driver/earnings': typeof DriverEarningsRoute
  '/_driver/home': typeof DriverHomeRoute
  '/_driver/notifications': typeof DriverNotificationsRoute
  '/_driver/profile': typeof DriverProfileRoute
  '/_driver/support': typeof DriverSupportRoute
  '/_driver/delivery/$orderId': typeof DriverDeliveryOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/deliveries'
    | '/earnings'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/support'
    | '/delivery/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/deliveries'
    | '/earnings'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/support'
    | '/delivery/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_driver'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_driver/deliveries'
    | '/_driver/earnings'
    | '/_driver/home'
    | '/_driver/notifications'
    | '/_driver/profile'
    | '/_driver/support'
    | '/_driver/delivery/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriverRoute: typeof DriverRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_driver': {
      id: '/_driver'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_driver/deliveries': {
      id: '/_driver/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DriverDeliveriesRouteImport
      parentRoute: typeof DriverRoute
    }
    '/_driver/earnings': {
      id: '/_driver/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/_driver/home': {
      id: '/_driver/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DriverHomeRouteImport
      parentRoute: typeof DriverRoute
    }
    '/_driver/notifications': {
      id: '/_driver/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DriverNotificationsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/_driver/profile': {
      id: '/_driver/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/_driver/support': {
      id: '/_driver/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof DriverSupportRouteImport
      parentRoute: typeof DriverRoute
    }
    '/_driver/delivery/$orderId': {
      id: '/_driver/delivery/$orderId'
      path: '/delivery/$orderId'
      fullPath: '/delivery/$orderId'
      preLoaderRoute: typeof DriverDeliveryOrderIdRouteImport
      parentRoute: typeof DriverRoute
    }
  }
}

interface DriverRouteChildren {
  DriverDeliveriesRoute: typeof DriverDeliveriesRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHomeRoute: typeof DriverHomeRoute
  DriverNotificationsRoute: typeof DriverNotificationsRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverSupportRoute: typeof DriverSupportRoute
  DriverDeliveryOrderIdRoute: typeof DriverDeliveryOrderIdRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverDeliveriesRoute: DriverDeliveriesRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHomeRoute: DriverHomeRoute,
  DriverNotificationsRoute: DriverNotificationsRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverSupportRoute: DriverSupportRoute,
  DriverDeliveryOrderIdRoute: DriverDeliveryOrderIdRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriverRoute: DriverRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
